```java
public class Test{
    public static void main(String[] args){
        //一段代码可能出现多种类型的异常
        fun(10,2);
        String str = null;
        System.out.println(str.length);
        
        //catch 匹配是从上到下的
        
        try{
            fun(10,2);
        	String str = null;
        	System.out.println(str.length);//空引用异常
        }catch(AritmeticException e){
            System.out.println("算数异常");
        }catch(NullPointerException e){
            //打印堆栈信息
            e.printStackTrace();
            
            System.out.println("空引用异常");
        }catch(Exception e){//父类放在最下面
            System.out.println("异常");
            e.printStackTrace();
        }
    }
    public void fun(){
        
    }
}
```

多重异常

不建议使用，建议分别处理

```java
try{
  …….
} catch(ArrayIndexOutOfBoundsException e) {
  ……
} catch(Exception e) {
  ……
}

try {
	i = a / b;
    System.out.println("try block");
} catch (IndexOutOfBoundsException | ArithmeticException e1) {
    System.out.println("发生异常，请处理该异常！");
}


```



​	•try语句块只能有一个，而catch语句块可以有任意多个

​	•catch语句块紧跟在try语句块之后

​	建议对捕获的异常做适当的处理，而不仅仅是打印异常信息

## finally语句块 

不管是否出现异常，都会执行，可以用来回收资源；



•finally语句定义一个总是被执行的代码块，而不考虑是否出现异常

​	–无论try、catch是否执行，finally必定执行

•不执行finally语句块的特殊情况

​	–在执行finally之前首先执行了“System.exit(0);”

•finally语句块典型应用

​	–回收资源

```java
		try{
            fun(10,2);
        	String str = null;
        	System.out.println(str.length);//空引用异常
            
            System.exit(0);//强制退出程序（不会执行finally语句块）
            
            
        }catch(AritmeticException e){
            System.out.println("算数异常");
        }catch(NullPointerException e){
            //打印堆栈信息
            e.printStackTrace();
            
            System.out.println("空引用异常");
        }catch(Exception e){//父类放在最下面
            System.out.println("异常");
            e.printStackTrace();
        }finally{
            //不管是否发生异常都会执行
            //作用：回收资源
            System.out.println("执行finally语句块");
        }
```

## 例子

```java
public static void main(String[] args) { 
      System.out.println("return value of test(): " + test(10,5)); 
      System.out.println("return value of test(): " + test(10,0));
} 
public static int test(int a, int b){
      int i = 0;  
      System.out.println("the previous statement of try block"); 
      try {
            i = a / b; 
            System.out.println("try block"); 
      }catch(Exception e){
            System.out.println("发生异常，请处理该异常！");
      }finally { 
            System.out.println("finally block,系统资源被释放！"); 
      }
      return i; 
}

//throws:声明该方法可能会抛出的异常类型
public void fun(int a,int b)throws AritmeticException
{
	if(b==0){
		//抛出异常的动作；
		AritmeticException e = new AritmeticException();
		throw e;
	}
	System.out.println(a/b); 
}





```





​	•如果JDK提供的异常类型不能满足需求的时候，程序员可以自定义一些异常类来描述自身程序中的异常信息。



​	•程序员自定义的异常类必须是Throwable的直接或间接子类。



​	•在程序中获得异常信息一般会调用异常对象的getMessage，printStackTrace，toString方法，所以自定义异常类一般会重写以上三个方法。

```java
public class IllegalAgeException extends RuntimeException{        
    //方法重写
    @Override
    public String getMessage(){
        return "年龄不符合要求"；
    }
    
    printStackTrace(){
        System.out.println(getMessage());
        super.printStackTrace();
    }
    
    @Override
    public String toString(){
        return "年龄不合法异常" + getClass().getName();//拼接上类名
    }
}

```



```java
//在学生类中调用
public void setAge(int age){
    if(age < 16|| age > 70){
        throw new IllegalAgeException();
    }
    this.age = age;
}
```

```java
Student stu = new Studnet();
stu.setAge(20);
```



```java
//public class IllegalAgeException extends Exception   不用try 就报错 //RuntimeException
try{
    Student stu = new Studnet();
	stu.setAge(20);
}catch(IllegalAgeException){
    e.printStackTrace();
}
```



•避免过大的try块，不要把不会出现异常的代码放到try块里面，尽量保持一个try块对应一个或多个异常。

•细化异常的类型，不要不管什么类型的异常都写成Excetpion。

•catch块尽量保持一个块捕获一类异常，不要忽略捕获的异常，捕获到后要么处理，要么重新抛出新类型的异常。

•不要把自己能处理的异常抛给别人。

•不要用try...catch控制程序流程，异常控制的**根本目的**是处理程序的非正常情况。



## 断点

不点运行   点小虫子（Debug）;

-|指向两个短线中间

## 数字格式异常NumberFormatException

```java
Integer i = new Integer("abc");
Double d = new Double("a");


```



## ClassNotFoundException

•常见原因：

​	–当使用第三方Jar包时，可能由于没导入包，或者包的版本不对，而导致该包中没有程序员用到的类。

•常见解决方法：

​	–导入该包。

​	–可以打开第三方Jar包，确认是否有该类，如果没有，可以更改包的版本。





